[build]
  publish = "build"
  command = "CI=false npm run build"

[build.environment]
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  ESLINT_NO_DEV_ERRORS = "true"
  TSC_COMPILE_ON_ERROR = "true"
  DISABLE_ESLINT_PLUGIN = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
